### ISSUE TITLE
Implement a build command

### ISSUE THREAD

**Issue by user-name-is-taken** [89luca89/lilipod#1]
This is probably possible using [buildkit](https://github.com/moby/buildkit) if you're open to adding a dependency or run buildkit inside a container in daemonless mode as described [here](https://hub.docker.com/r/moby/buildkit) with a command similar to this:

```
docker run \
    -it \
    --rm \
    --privileged \
    -v /path/to/dir:/tmp/work \
    --entrypoint buildctl-daemonless.sh \
    moby/buildkit:master \
        build \
        --frontend dockerfile.v0 \
        --local context=/tmp/work \
        --local dockerfile=/tmp/work
```

**Comment by 89luca89** [comment]
Will investigate this @user-name-is-taken 
thanks :smile:
