### ISSUE TITLE
lilipod rm does not work.

### ISSUE THREAD

**Issue by KDBalashevich** [89luca89/lilipod#15]
I have an image created by distrobox.
If I try to **distrobox-rm** it, I can still see it in **distrobox list**, however if I try to delete it again, i get a messege, that there are no containers with that name.
If I try to delete it with **lilipod rm**, I get the same result.
However I can still see it in **lilipod ps -a** output. 
**lilipod rm -a** deletes everything successfully

**Comment by mirkobrombin** [comment]
What's the output of `lilipod rm`?

**Comment by KDBalashevich** [comment]
For whatever reason I cannot reproduce the issue now.
