### ISSUE TITLE
Add license to repository

### ISSUE THREAD

**Issue by alegrey91** [89luca89/lilipod#4]
Currently, the LICENSE file is missing.
You should add this in order to preserve your rights.

**Comment by osalbahr** [comment]
Could you elaborate on "to preserve your rights"? To the best of my understanding, the default is [all rights are reserved](https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license). So adding a license alleviates some restrictions (which is good).
